services:
  invest-app:
    container_name: invest-app
    build: .
    environment:
      SPRING_JDBC_URL: jdbc:mysql://db:3306/invest
      SPRING_JDBC_USERNAME: root
      SPRING_JDBC_PASSWORD: password
    ports:
      - "8888:8888"
    depends_on:
      - invest-database
    networks:
      - app-network

  invest-database:
    container_name: invest-db
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: invest
    ports:
      - "3333:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
networks:
  app-network:

volumes:
  mysql_data: